---
- name: test
  hosts: all
  gather_facts: yes
  vars:
    distro: "{{ ansible_facts.distribution_release }}"
    hostname: "{{ ansible_facts.hostname }}"

  tasks:
    - name: adding repos
      import_tasks: tasks/repo.yml
      when: repos is defined
      become: true
    
    - name: adding package
      import_tasks: tasks/packages.yml
      when: packages is defined
      become: true

    - name: adding snap
      import_tasks: tasks/snapcraft.yml
      when: snap is defined
      become: true

    - name: cloning git repos
      import_tasks: tasks/git.yml
      when: git is defined
      ignore_errors: yes

    - name: install go tools
      import_tasks: tasks/go.yml
      when: go is defined

    - name: install pip packages
      import_tasks: tasks/pip.yml
      when: pip is defined

    - name: install npm packages
      import_tasks: tasks/npm.yml
      when: npm is defined

    - name: run shell commands
      import_tasks: tasks/command.yml
      when: command is defined
