- name: Installing packages apt based
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.apt }}"
  when:
    - ansible_facts['os_family'] == 'Debian'
    - packages.apt is defined

- name: Install packages yum based
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.yum }}"
  when: 
    - ansible_facts['os_family'] == 'RedHat'
    - packages.yum is defined
