# Apt

# - name: print var
#   shell: echo {{item.apt.repo}}
#   loop: "{{ repos }}"

- name: updating repos
  apt:
    name: '*'
    state: latest
    pkg:
    - wget
    - curl
    - apt-transport-https
  when:
    - ansible_os_family == 'Debian'
    - item.apt is defined

- name: Adding keys for {{ item.name }}
  apt_key:
    url: "{{ item.apt.key }}"
    state: present
  loop: "{{ repos }}"
  when:
    - ansible_os_family == 'Debian'
    - item.apt is defined
    - item.apt.key is defined

- name: "Adding repo for {{ item.name }}"
  apt_repository:
    filename: "{{ item.name | replace('.','-') | replace(' ','-') | lower }}"
    repo: "{{ item.apt.repo }}"
    state: present
  loop: "{{ repos }}"
  when: 
    - ansible_os_family == 'Debian'
    - item.apt is defined

- name: "update and install repo packages"
  apt:
    name: "{{ item.apt.packages }}"
    state: latest
  loop: "{{ repos }}"
  when:
    - ansible_os_family == 'Debian'
    - item.apt is defined
    - item.apt.packages is defined

# Yum

- name: Import a key from a url
  rpm_key:
    state: present
    key: "{{ item.yum.key }}"
  loop: "{{ repos }}"
  when: 
    - ansible_os_family == 'RedHat'
    - item.yum.key is defined

- name: Add multiple repositories into the same file (1/2)
  shell: "yum-config-manager --add-repo {{ item.yum.repo }}"
  loop: "{{ repos }}"
  when:
    - ansible_os_family == 'RedHat'
    - item.yum is defined

- name: Install packages repo based
  yum:
    name: "{{ item.yum.packages }}"
    state: latest
  loop: "{{ repos }}"
  when:
    - ansible_os_family == 'RedHat'
    - item.yum is defined
