# Install snap packages 

- name: installing {item.name}
  snap:
    name: "{{ item }}"
    state: present
    classic: no
  loop: "{{ snap.packages }}"
  when: snap.packages is defined

# snap classic packages
- name: installing classic {item.name}
  snap:
    name: "{{ item }}"
    state: present
    classic: yes
  loop: "{{ snap.classic }}"
  when: snap.classic is defined
